### ISSUE TITLE
java.lang.NoClassDefFoundError: com.enrique.mymodule.app.R$string

### ISSUE THREAD

**Issue by se-rg-os** [kikoso/AppRate-for-Android#5]
Hi, guys, 
I am willing to add your component to  my Android project using Android Studio and gradle. 
After adding it directly as a dependency in gradle file like: 

```
compile 'com.github.kikoso:AppRate-Android:1.0-RELEASE'
```

my project successfully compiles and I can import `AppRater` in my `Application` class. But as soon as I try to create `new AppRater(getApplicationContext())` and run app I am receiving error like: 

```
com.application.appratertest E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.application.appratertest, PID: 30907
    java.lang.NoClassDefFoundError: com.enrique.mymodule.app.R$string
            at com.enrique.apprater.AppRater.showRateDialog(AppRater.java:57)
            at com.enrique.apprater.AppRater.init(AppRater.java:47)
```

Can you please provide some instructions of how I can add AppRater properly when using Android Studio and gradle ? Thank you!

**Comment by claudsan** [comment]
same here

**Comment by Maddumage** [comment]
same to me
